### ISSUE TITLE
draw_arc is not declared in the current class

### ISSUE THREAD

**Issue by john-wilkinson** [wesnoth/haldric#113]
Just cloned this project and loaded it in godot and tried to run it. It crashes on https://github.com/wesnoth/haldric/blob/a9a2d6688ddad28bcc1164667dfca33ca470b13a/source/interface/hud/ToDWheel.gd#L20

`Method 'draw_arc' is not declared in the current class`

Very new to godot, so it could be I have a dependency problem that i'm not sure how to resolve.

Checked the contributing guide but didn't see anything about dependencies or a getting started guide or anything

**Comment by Byteron** [comment]
Which version of Godot are you using?

**Comment by john-wilkinson** [comment]
I am using 3.1.2

**Comment by iwek7** [comment]
From what I see `draw_arc` was added some 3 months ago so it is not present in Godot 3.1.x, you can grab newer version from here (3.2rc3 : https://downloads.tuxfamily.org/godotengine/3.2/rc3/)

**Comment by iwek7** [comment]
However rc3 seems to throw yet another exception for me `Cannot asign Nil to Vector3 variable` in https://github.com/wesnoth/haldric/blame/master/source/game/Game.gd#L210 .

**Comment by iwek7** [comment]
Should be all good now, current master runs normally for me, if someone else confirms I think we can close it

**Comment by Byteron** [comment]
seems to be working now, hence closing this.
