### ISSUE TITLE
Pressing the attack button when the unit is moving stops the unit

### ISSUE THREAD

**Issue by jay20162016** [wesnoth/haldric#120]
When you press the attack button when the unit is still moving, the unit stops moving and attacks. However, the unit may not be directly next to the target.

**Comment by iwek7** [comment]
So I took a look at this issue and have some thoughts

There seem to be multiple issues with this mechanic. First of all attack popup (with attack types) appear imminently after player attempts to move to field that is occupied by another unit. So for instance, if player movement is halted by new enemies appearing, attack popup that was shown at the beginning of movement remains. Here is an example (scout was moving).

![image](https://user-images.githubusercontent.com/9964886/80377006-ee258980-889a-11ea-9353-782fd2593c27.png)

Code responsible for this is in `Game` class:
```
 if loc.unit and loc.unit != current_unit:
                    HUD.show_attack_popup(current_unit, loc.unit)
```

I think proper fix would be showing popup when enemy is successfully approached. Fix seems simple - but I'm not really sure how to do this. 

One approach would be to store new state of unit - intent of attack (along with target) that is checked at the end of the movement. If movement was not halted and unit is intending to  attack then we could issue a signal to `Game` to show attack popup. However, this approach has some shortcomings, biggest of which is spliting attack-move action into two separate actions and keeping their states in separate places, which might cause transactional issues - for instance I fear that intention of attack won't be cleared properly in some edge cases we can't foresee.

The solution I like a bit more is creating whole new unit state - some kind of `MoveAttack`. This state would check if position for proper attack was reached and then issue signal if so. The state would have information about attack target. The disadentage here is duplicating code from `Move` class.

**Comment by Byteron** [comment]
I think you should know your options before you approach.
Having the popup popping up before the unit moves I think is the right call.
Though we certainly can handle it better.

**Comment by iwek7** [comment]
Maybe we should just wait for user to select attack option before moving as it is the case in wesnoth?

**Comment by Byteron** [comment]
Yes, I think so too.

**Comment by Byteron** [comment]
closing this too, as the combat logic as been reworked.
