### ISSUE TITLE
Map is redrawn three times per rendering loop

### ISSUE THREAD

**Issue by ImperatorS79** [wesnoth/haldric#130]
Hi,

I am not an expert in graphics engine, but since I got terrible performance running haldric on my old laptop (13 fps while it is 40 fps with main wesnoth), I decided to run it through renderdoc on my other computer to see what is happening.

Since renderdoc does not support capture with OpenGL 2, the capture is full of not batched drawcall (The tilemap seems to be drawn with one drawcal per hexagon using the godot GLES3 renderer ! But the GLES2 godot renderer supports batching :/).

But what seems the strangest to me is that the map is drawn **entirely** three times per "rendering loop": once for the main map, once for the unit zoom and once for the minimap.

I guess you could renderer the minimap to a texture and display it, use that texture as a base to draw the full map to a texture and display it, and use that final texture to draw the unit zoom, thus dividing the amount of draw calls per loop per three (I think in godot you could use godot "viewports" to do this ? -> https://docs.godotengine.org/en/stable/tutorials/viewports/viewports.html).

I hope I did not bother you recalling something you already knew ^^.

Thanks for the amazing work on wesnoth 👍.

**Comment by asheraryam** [comment]
This would actually be very easy to implement, using the node [ViewportContainer](https://docs.godotengine.org/en/stable/classes/class_viewportcontainer.html) as the parent of a Viewport will automatically make render it to the screen, and then for the minimap and unit zoom then can use the Viewport data as well.

**Comment by Byteron** [comment]
the minimap is gone in master and will be reimplemented eventually. Closing this as this has no relevance at this point.
