### ISSUE TITLE
Units become unselectable after stopping a move unexpectedly in the same hex as another unit

### ISSUE THREAD

**Issue by derkus** [wesnoth/haldric#139]
### Summary:
A unit can become unselectable if its movement ends while it occupies a space with another unit. I have been able to reliably reproduce the bug with the steps below, and have also had it occur in a number of other situations with other units.

### Steps to Reproduce:
1. Load the test scenario.
2. Move the Elf Fighter a space Northeast and another space North
3. Move the Elvish Scout 4 spaces northeast (just southeast of the village) 
4. End the turn twice to (returning to the top of the players turn)
5. Select the Elvish Fighter and attempt to move 3 hexes northeast (just past the Scout)
6. The Fighter will move and stop on top of the Scout. (Figure 3)

Figure 1: Setup
![image](https://user-images.githubusercontent.com/18131389/83956812-ca991b80-a816-11ea-9b91-b5c7aba30ac0.png)

Figure 2: Move Attempt
![image](https://user-images.githubusercontent.com/18131389/83956832-de448200-a816-11ea-9bd4-452864411860.png)

Figure 3: Move Results
![image](https://user-images.githubusercontent.com/18131389/83956836-e8ff1700-a816-11ea-92a8-ea0309d0a585.png)

### Expected Results:
I had expected to have the unit move through the other unit to the hex on the far side.

### Actual Results:
The moving Elvish Fighter stops in the hex occupied by the Elvish Scout and becomes non-selectable. The Scout can move away and performs normally, however the fighter can not be interacted with after that point.

**Comment by jay20162016** [comment]
I think this issue is already known, however we are currently (as far as I know) using the experimental branch, which has many features, and doesn't have this but (yet).

**Comment by Byteron** [comment]
pretty sure that is not the case with the new movement logic. Closing this.
