### ISSUE TITLE
Proposal: Stackable Units

### ISSUE THREAD

**Issue by Byteron** [wesnoth/haldric#17]
Currently units of a player are able to:

1. move through other units
2. get stuck on a tile where a unit already stands on, when the ZoC of an enemy unit kicks in

That needs to be fixed.

**Comment by Byteron** [comment]
Is that actually a proposal to allow multiple units on a tile, or should the stack cost per tile just be 1?

**Comment by GregoryLundberg** [comment]
You asked and it's my proposal.  What I was thinking was that there be a "Wesnoth 1" ruleset mode which sets the stack limit to 1 but new content could be rebalanced to allow stacking. It's an idea I've been considering for 1.15, but, there, the stack limit would actually be 1 unless a UMC author changed it.

**Comment by Byteron** [comment]
So far we haven't talked about changes to the game play, thus I presumed it should not be possible and therefore is a simple bug that has to be fixed, not something that we might want to keep as a feature.

Though an alternate ruleset that can be toggled on and off might be something to consider.

Then again, stacking units comes with a lot of things that need to be considered.
Like what happens when a unit attacks a tile on which multiple other units stand. Do their strength/health get combined somehow? can they be moved as a bonded group as it would be one unit? what happens with abilities that affect "adjacent units" - would a unit on the same tile count as adjacent unit? - there's a lot.

**Comment by Byteron** [comment]
So right now, units should not be able to get stuck on the same tile anymore, but it's still the question whether or not we implement "stackable units" as a feature for a possible new game playe mode.

**Comment by mathpeseg** [comment]
I think it would be nice if when you click on stacked units a menu on the left of the screen shows wich units are there, and you can just move with all of them without touching the menu, or chose one unit on the menu to move it alone off of the stack. 
Attacks could also use the menu to work. Being able to attack with all the units by not clicking on the menu, or just one of them using the menu. This would allow 1 tile with 6 units to battle with 6 units surrounding this tile. Of course stack should only be able with units of the same type.

**Comment by GregoryLundberg** [comment]
I was thinking something like how civ (or is it freeciv): have a default (move all, move only topmost/visible); right-click to get a (scrolling) check list to allow you to pick and choose with move up/down to change stack order. For offense, have a default (most melee damage, or topmost/visible). For defense, have a default (best defense, topmost, best counter). etc etc

**Comment by GregoryLundberg** [comment]
So change the stack order (for defense) or select the unit to move/attack. The point of the defaults is to make them the choice when you don't. Not our problem is you don't actually choose what you wanted.

**Comment by LawnCable** [comment]
Move all would need to respect different movement points and possibly different reach over different terrain for the different units.

**Comment by Byteron** [comment]
I think Stackable Units are ruled out, as we want to keep gameplay close to the original.
having units not stack is an essential element of the gameplay in 1.x
Will close this for now.
