### ISSUE TITLE
World Scaling

### ISSUE THREAD

**Issue by Byteron** [wesnoth/haldric#25]
I once read that one hex tile in Wesnoth is about one mile in length. Given that a day in Wesnoth usually lasts 6 turns, and in each turn the usual infantry moves 5 tiles, this is about 30 hexes / miles per day, (if moving 24/7), which does seem reasonable to me.
What does _not_ though, is the fact that characters in campaigns use to talk to each other without issues even though there are several hexes, thus miles, between them.

Since we're doing this game pretty much from scratch and we also talked about new HD terrain, we could rethink the scales of a hex. Units are treated as single persons all the time already, so we might actually make them single persons, and a single hex tile could me meters, not miles, as an example.

What are your thoughts about this? Your ideas?

**Comment by beetlenaut** [comment]
On Monday, October 22, 2018 5:06:08 AM PDT Aaron Winter wrote:
> I once read that one hex tile in Wesnoth is about one mile in length.

No, hexes are *perhaps* a mile in length. Sometimes they are much smaller. It 
depends on the map and what you are doing. While you are sending scouts to get 
gold, hexes might be miles across, but when the armies meet, the soldiers are 
probably a few feet from each other. Some maps are inside a house where the 
hexes are definitely quite small. The scale is not supposed to be defined, and 
I think it would break Wesnoth to define it.

I'm not saying it's a terrible idea, just that it would be a very different 
game at that point.

---Dan

**Comment by Pentarctagon** [comment]
To add to that, there's the acronym HAPMA(Hexes Are Possibly Miles Across) from [here](https://wiki.wesnoth.org/Glossary#General_Acronyms).

**Comment by davewx7** [comment]
Wesnoth is a somewhat abstracted strategy game. We don't worry about details like the literal dimensions of a tile if it were to be converted to real-world space. 

When we make decisions about gameplay, art, and so forth, we do so on the basis of what provides the best experience for the player. Additional constraints such as having to match some arbitrary tile dimensions are not something that we want to deal with.

**Comment by Byteron** [comment]
You guys have some good points on this. Also, it seems you have common grounds in that matter, so I guess it's save to close this issue again. :P
