### ISSUE TITLE
cover.shader/cover.tres blur element doesn't seem to be working anymore

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/haldric#47]
See topic

**Comment by Byteron** [comment]
It works just fine for me.
Blur is set to quite a low value (0.2), maybe that's why you don't see it.
I tested by setting it to 2.0. Totally blurry.

**Comment by Vultraz** [comment]
Turns out it does work, nevermind. Was looking at the wrong file 🤦‍♂️
