### ISSUE TITLE
pause between unit steps

### ISSUE THREAD

**Issue by Byteron** [wesnoth/haldric#48]
When moving a unit, it seems there is a pause between the unit arriving a tile and start moving to the next tile.

This happens since we introduced FSM to Unit.tscn

Note: Currently the tween is set to TRANS_SINE. This pause also happens when it's set to TRANS_LINEAR.

it appears to be a severe performance drop, so it should definitely be investigated further.

**Comment by 20kdc** [comment]
I was curious about this, poked at it in the profiler, and... it seems setting a unit's location causes it to update viewability and reachability, and that's presumably happening as the unit is moved in Move.gd.
Move.gd then also refreshes viewability and reachability after cost is subtracted from moves\_current.

**Comment by Byteron** [comment]
fixed by commit 1ef4081
