### ISSUE TITLE
Poor performance on integrated Graphics

### ISSUE THREAD

**Issue by LawnCable** [wesnoth/haldric#50]
When I run it from the editor loading a game screen takes long sometimes I get the whole game to freeze for a few seconds.
Loading the test scenario has loads without user feedback ~6 seconds after the progress bar is already done.
Also I only get like 36 fps in the test scenario and drops when i move units as low as 26 fps.
The exported version is only like 6 fps better but still drops down to 27.
(I'm on a laptop using Linux)

Anyways Performance on lower end hardware is also an important thing we should keep in mind.

**Comment by Byteron** [comment]
@LawnCable
Which CPU do you have, and do you have a HDD or SDD hard drive?
I get similar fps on my notebook (which most likely is due to the shaders) but loading times are much faster, not even a second.

**Comment by LawnCable** [comment]
After plugging it in the main powers the fps of the exported game was a more stable ~40 fps.
- CPU is `Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz` with 8 cores/threads
- And I have an SSD with the btrfs file system ( I could spin up a ram disk if you think that could help)

**Comment by Zireael07** [comment]
"Internal graphics" being what exactly? There's a ton of different Intel integrated cards out there...

**Comment by Byteron** [comment]
The i5-8259U has Intel® UHD Graphics 620.
Interestingly enough, it *should* perform better than my Intel HD Graphics 530.
Also it has double the amount of cores/threads than mine. (I have 2 cores/ 4 threads), so neither CPU nor hard drive should bottleneck here.

**Comment by Byteron** [comment]
I double checked just now, current master (a4f4e9b) gives me a loading time of 0.79 seconds (checked with the build in profiler)

**Comment by LawnCable** [comment]
@Byteron which version of godot are you using?

**Comment by Byteron** [comment]
@LawnCable Version is Godot 3.1-stable on Linux.

**Comment by LawnCable** [comment]
I opened a separate issue(#53) for the log loading times, so that we can concentrate on the fps-performance issue here.

**Comment by Byteron** [comment]
@LawnCable there were a few commits regarding performance in the last few days.
Would you mind checking again if you still have low fps counts?
On my Laptop I get fps ranging from 47-60 in the test scenario, running on intel integrated graphics. (i5 6300-HQ with 530 HD Graphics)

**Comment by LawnCable** [comment]
Its better, but the frames drop still under ~30 when moving units

**Comment by LawnCable** [comment]
yesterday that was, now its worse again 24 avg with profiler enabled

**Comment by LawnCable** [comment]
Ok, 50 fps without profiler and doing anything.
When moving unit or ending round it drops to ~33. (without profiler)

**Comment by Byteron** [comment]
I consider closing this issue as performance optimisations like this are way too early to discuss, given that we just started building haldric, as most of what is in now is subject to change anyways.
This may be reopened to a later point in time again.
