### ISSUE TITLE
Advancements

### ISSUE THREAD

**Issue by Byteron** [wesnoth/haldric#56]
When the experience of a unit reaches it's maximum, a unit shall advance.

- [ ] advancing to a higher level unit
- [ ] possibility to choose between multiple advancements

**Comment by LawnCable** [comment]
The api should allow for custom levelup behaviour in mods, I saw it used in wesnoth 1.x  extentions.

**Comment by Byteron** [comment]
There was talk about an AMLA overhaul. I'll make that a separate issue.
