### ISSUE TITLE
unit visibility

### ISSUE THREAD

**Issue by Byteron** [wesnoth/haldric#63]
Units from side 2 can see units from side 1, but units from side 1 cannot see units from side 2 for some reason.

**Comment by Arc-dev** [comment]
Oddly it's only on vision, side 1 units can't move into the same tile occupied by side 1.

**Comment by Byteron** [comment]
IIRC visibility is not yet respected when calculating reachable/viewable tiles.

**Comment by Byteron** [comment]
this was fixed by commit 3259dc2
