### ISSUE TITLE
Main menu freezes when coming back to Home

### ISSUE THREAD

**Issue by aalonso99** [wesnoth/haldric#74]
If you select other option, like "Campaigns" and then select "Home" back, the whole menu freezes.
I run it in Godot 3.1.1 stable with the following set up:

Ubuntu 18.04.3 LTS 64bits
7.7GB of DDR3 RAM
Processor Intel® Core™ i5-4210U CPU @ 1.70GHz × 4 
Graphic Card GeForce 940M/PCIe/SSE2

**Comment by GaidamakUA** [comment]
Thank you for your report. It's work in progress. For now you can use arrows.

**Comment by Byteron** [comment]
Can't reproduce this issue. Has this been fixed?

**Comment by iwek7** [comment]
Also can't reproduce
