### ISSUE TITLE
Traits

### ISSUE THREAD

**Issue by db0** [wesnoth/haldric#84]
As per the original: When units are recruited they should receive 2 traits from a random choice selection according to their race (e.g. Strong/Intelligent/Resilient etc). Undead should receive only 1 trait always: Undead

**Comment by Byteron** [comment]
I guess we need to define races first to give them traits based on their race.

**Comment by db0** [comment]
Eventually, but initially we can just setup the engine with a common list

**Comment by Byteron** [comment]
Closing, as traits are supported now.
