### ISSUE TITLE
Income & Upkeep

### ISSUE THREAD

**Issue by db0** [wesnoth/haldric#85]
Player needs to receive income based on the number of villages they control. Player needs to pay upkeep based on the number of units they own

- [x] Income is: 2 base + 1 per village you control
- [x] Upkeep is: 1 gold per unit level
- [ ] Unit with Loyal #84 Trait and Leaders do not cost upkeep

**Comment by Byteron** [comment]
also, each single village covers the upkeep cost of a single unit.

**Comment by db0** [comment]
That's not accurate. Effectively each village covers the upkeep of a unit *level*.

**Comment by Byteron** [comment]
Oh? I thought it covers an entire unit.
But well that makes things easier cuz then it's just simple math.
no fiddling around with what unit to cover.

**Comment by Byteron** [comment]
upkeep is now working properly, including loyal trait.
