### ISSUE TITLE
Healing

### ISSUE THREAD

**Issue by db0** [wesnoth/haldric#86]
Units need to be able to heal HP. Basic methods (i.e. without involving abilities or traits)

- [x] A unit that does not move or is involved in an attack heals 2 HP on its next turn
- [x] A unit which starts its turn in a village or oasis, heals 8 HP

**Comment by db0** [comment]
For reference, abilities & traits which also heal are:

- [ ] Regeneration Trait (8 HP or cure poison)
- [ ] Heals ability (4 ot 8 HP per turn)
- [ ] Advancement (full heal)

**Comment by Byteron** [comment]
the dwarves "healthy" trait also regenerates them +2 per turn I think.
