### ISSUE TITLE
Add Godot/GDScript/C# learning resources to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Elvish-Hunter** [wesnoth/haldric#95]
Some people would like to help contributing to the Haldric engine, but they might never have used Godot so far. Would it be possible adding to the `CONTRIBUTING.md` file (or to another file, in case that one becomes too long) a list of good resources to learn how to use Godot and how to program in GDScript and C#?

**Comment by Byteron** [comment]
Added a few links. Leaving the issue open to remind us to add more resources.
(There is more good stuff out there, for now I added just a few to point at least somewhere)

**Comment by Byteron** [comment]
I think the provided links are enough to get people started. Closing this.
